# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx1072m -DskipTests=true'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerhub'
      repository: 'duzaporozhets/web-app'
      command: 'buildAndPush'
      Dockerfile: 'docker/WebApp'
      buildContext: '.'
      tags: 'v2.$(Build.BuildId)'
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerhub'
      repository: 'duzaporozhets/db-app'
      command: 'buildAndPush'
      Dockerfile: 'docker/Database'
      buildContext: '.'
      tags: 'v2.$(Build.BuildId)'
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'k8'
      Contents: |
        database-config-map.yaml
        database-deployment.yaml
        database-pv-azure.yaml
        database-secret.yaml
        mvc-deployment.azure.yaml
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'drop'
      publishLocation: 'pipeline'
  - task: replacetokens@4
    inputs:
      rootDirectory: $(Build.ArtifactStagingDirectory)
      targetFiles: |
        mvc-deployment.azure.yaml
        database-deployment.yaml
      encoding: 'auto'
      tokenPattern: 'default'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      actionOnNoFiles: 'continue'
      enableTransforms: false
      useLegacyPattern: false
      enableTelemetry: true