apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-deployment
  labels:
    app: mvc
spec:
  selector:
    matchLabels:
      app: mvc
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
        - name: mvc
          image: duzaporozhets/web-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: db-password-secret
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: db-url-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-service
spec:
  selector:
    app: mvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30100
  type: NodePort